
# Workflow name
name: 'Update npm version'

# Event for the workflow
on:
  push:
    branches:
      - cumi


# List of jobs
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook

      - name: Update npm package version
        run: |
          git config --global user.name "${{ env.USERNAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"
          npm version minor

      - name: Publish npm package version
        run: npm publish